version: '3.8'

# Override file for production environment
# This file contains environment-specific configurations

services:
  mysql:
    environment:
      # Ensure MySQL uses proper environment variables
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_root_password
      MYSQL_USER_FILE: /run/secrets/mysql_user
      MYSQL_PASSWORD_FILE: /run/secrets/mysql_password
    secrets:
      - mysql_root_password
      - mysql_user
      - mysql_password

  backend:
    environment:
      # Override Django settings for production
      DJANGO_SETTINGS_MODULE: core.settings
      DJANGO_DEBUG: '0'
      DJANGO_SECURE_SSL_REDIRECT: '1'
      DJANGO_SECURE_HSTS_SECONDS: '31536000'
      DJANGO_SECURE_HSTS_INCLUDE_SUBDOMAINS: '1'
      DJANGO_SECURE_HSTS_PRELOAD: '1'

secrets:
  mysql_root_password:
    file: ./secrets/mysql_root_password.txt
  mysql_user:
    file: ./secrets/mysql_user.txt
  mysql_password:
    file: ./secrets/mysql_password.txt
