version: '3.8'

services:
  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: absensi_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: absensi_db
      MYSQL_USER: absensi_user
      MYSQL_PASSWORD: absensi_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d
    networks:
      - absensi_network
    command: --default-authentication-plugin=mysql_native_password

  # phpMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: absensi_phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: rootpassword
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "8080:80"
    depends_on:
      - mysql
    networks:
      - absensi_network

  # Backend DRF
  backend:
    build:
      context: ./drf
      dockerfile: Dockerfile
    container_name: absensi_backend
    restart: unless-stopped
    environment:
      - DJANGO_DEBUG=0
      - DJANGO_SECRET_KEY=your-super-secret-key-change-this-in-production
      - DJANGO_ALLOWED_HOSTS=localhost,127.0.0.1,backend
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=absensi_db
      - MYSQL_USER=absensi_user
      - MYSQL_PASSWORD=absensi_password
      - CORS_ORIGIN_FRONTEND=http://frontend:3000
    ports:
      - "8000:8000"
    depends_on:
      - mysql
    networks:
      - absensi_network
    volumes:
      - ./drf/app:/app

  # Frontend Next.js
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: absensi_frontend
    restart: unless-stopped
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
      - NEXT_PUBLIC_BACKEND_URL=http://backend:8000
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - absensi_network
    volumes:
      - ./frontend:/app
      - /app/node_modules

volumes:
  mysql_data:
    driver: local

networks:
  absensi_network:
    driver: bridge
