version: '3.8'

services:
  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: absensi_mysql_dev
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: absensi_db
      MYSQL_USER: absensi_user
      MYSQL_PASSWORD: absensi_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data_dev:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d
    networks:
      - absensi_network_dev
    command: --default-authentication-plugin=mysql_native_password

  # phpMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: absensi_phpmyadmin_dev
    restart: unless-stopped
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: rootpassword
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "8080:80"
    depends_on:
      - mysql
    networks:
      - absensi_network_dev

  # Backend FastAPI (Development)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: absensi_backend_dev
    restart: unless-stopped
    environment:
      - DATABASE_URL=mysql+pymysql://absensi_user:absensi_password@mysql:3306/absensi_db
      - SECRET_KEY=dev-secret-key-change-in-production
      - PASSWORD_SALT=dev-password-salt-change-in-production
      - BACKEND_CORS_ORIGINS=["http://localhost:3000", "http://frontend:3000"]
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
    ports:
      - "8000:8000"
    depends_on:
      - mysql
    networks:
      - absensi_network_dev
    volumes:
      - ./backend:/app
      - /app/.venv
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

  # Frontend Next.js (Development)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: absensi_frontend_dev
    restart: unless-stopped
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
      - NEXT_PUBLIC_BACKEND_URL=http://backend:8000
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - absensi_network_dev
    volumes:
      - ./frontend:/app
      - /app/node_modules

volumes:
  mysql_data_dev:
    driver: local

networks:
  absensi_network_dev:
    driver: bridge
