# Generated by Django 5.0.2 on 2025-08-25 23:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date_local', models.DateField()),
                ('timezone', models.CharField(max_length=64)),
                ('check_in_at_utc', models.DateTimeField(blank=True, null=True)),
                ('check_in_lat', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('check_in_lng', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('check_in_accuracy_m', models.PositiveIntegerField(blank=True, null=True)),
                ('check_in_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Check-in IP Address')),
                ('check_out_at_utc', models.DateTimeField(blank=True, null=True)),
                ('check_out_lat', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('check_out_lng', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('check_out_accuracy_m', models.PositiveIntegerField(blank=True, null=True)),
                ('check_out_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Check-out IP Address')),
                ('is_holiday', models.BooleanField(default=False)),
                ('within_geofence', models.BooleanField(default=False)),
                ('minutes_late', models.IntegerField(default=0)),
                ('total_work_minutes', models.IntegerField(default=0)),
                ('note', models.CharField(blank=True, max_length=200, null=True)),
                ('employee_note', models.TextField(blank=True, null=True)),
                ('overtime_minutes', models.PositiveIntegerField(default=0, help_text='Minutes worked beyond required work hours', verbose_name='Overtime Minutes')),
                ('overtime_amount', models.DecimalField(decimal_places=2, default=0, help_text='Calculated overtime pay amount', max_digits=12, verbose_name='Overtime Amount')),
                ('overtime_approved', models.BooleanField(default=False, help_text='Whether overtime has been approved by supervisor', verbose_name='Overtime Approved')),
                ('overtime_approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Overtime Approved At')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendances', to='employees.employee')),
                ('overtime_approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_attendance_overtimes', to=settings.AUTH_USER_MODEL, verbose_name='Overtime Approved By')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Attendance',
                'verbose_name_plural': 'Attendances',
                'ordering': ['-date_local', '-created_at'],
                'unique_together': {('user', 'date_local')},
            },
        ),
    ]
