# Generated by Django 5.0.2 on 2025-09-17 08:32

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.ForeignKey(blank=True, help_text='DEPRECATED: Use positions many-to-many relationship instead', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legacy_employees', to='employees.position', verbose_name='Legacy Position'),
        ),
        migrations.AlterField(
            model_name='position',
            name='approval_level',
            field=models.PositiveSmallIntegerField(choices=[(0, 'No Approval'), (1, 'Division Level'), (2, 'Organization Level')], default=1, help_text='0 = No approval permission, 1 = Division-level approval, 2 = Organization-level (final) approval', verbose_name='Approval Level'),
        ),
        migrations.CreateModel(
            name='EmployeePosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_primary', models.BooleanField(default=False, help_text='Primary position for the employee', verbose_name='Is Primary Position')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this position assignment is active', verbose_name='Is Active')),
                ('effective_from', models.DateField(default=datetime.date.today, help_text='When this position becomes effective', verbose_name='Effective From')),
                ('effective_until', models.DateField(blank=True, help_text='When this position expires (optional)', null=True, verbose_name='Effective Until')),
                ('assignment_notes', models.TextField(blank=True, help_text='Reason or notes for this position assignment', verbose_name='Assignment Notes')),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_positions', to=settings.AUTH_USER_MODEL, verbose_name='Assigned By')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_positions', to='employees.employee')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='position_employees', to='employees.position')),
            ],
            options={
                'verbose_name': 'Employee Position',
                'verbose_name_plural': 'Employee Positions',
                'ordering': ['-is_primary', '-is_active', '-effective_from'],
                'unique_together': {('employee', 'position')},
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='positions',
            field=models.ManyToManyField(related_name='employees', through='employees.EmployeePosition', to='employees.position', verbose_name='Positions'),
        ),
    ]
