# Generated by Django 5.0.2 on 2025-09-18 03:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_migrate_legacy_positions_to_multi_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='active_position',
            field=models.ForeignKey(blank=True, help_text='Currently active position context for this employee', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_for_employees', to='employees.employeeposition', verbose_name='Active Position'),
        ),
    ]
