# Generated by Django 5.2.5 on 2025-08-13 11:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_employee_gaji_pokok_employee_tanggal_lahir_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('note', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='WorkSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timezone', models.CharField(default='Asia/Dubai', max_length=64)),
                ('start_time', models.TimeField(default=datetime.time(9, 0))),
                ('end_time', models.TimeField(default=datetime.time(17, 0))),
                ('required_minutes', models.PositiveIntegerField(default=480)),
                ('grace_minutes', models.PositiveIntegerField(default=0)),
                ('workdays', models.JSONField(default=[0, 1, 2, 3, 4])),
            ],
            options={
                'verbose_name': 'Work Settings',
                'verbose_name_plural': 'Work Settings',
            },
        ),
    ]
