# Generated by Django 5.2.5 on 2025-08-13 11:14

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_holiday_worksettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worksettings',
            name='workdays',
            field=models.JSONField(default=api.models.WorkSettings._default_workdays),
        ),
    ]
