# Generated by Django 5.2.5 on 2025-08-13 15:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_worksettings_workdays'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='worksettings',
            name='office_latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='worksettings',
            name='office_longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='worksettings',
            name='office_radius_meters',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_local', models.DateField()),
                ('timezone', models.CharField(max_length=64)),
                ('check_in_at_utc', models.DateTimeField(blank=True, null=True)),
                ('check_in_lat', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('check_in_lng', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('check_in_accuracy_m', models.PositiveIntegerField(blank=True, null=True)),
                ('check_out_at_utc', models.DateTimeField(blank=True, null=True)),
                ('check_out_lat', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('check_out_lng', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('check_out_accuracy_m', models.PositiveIntegerField(blank=True, null=True)),
                ('is_holiday', models.BooleanField(default=False)),
                ('within_geofence', models.BooleanField(default=False)),
                ('minutes_late', models.IntegerField(default=0)),
                ('total_work_minutes', models.IntegerField(default=0)),
                ('note', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendances', to='api.employee')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_local', '-created_at'],
                'unique_together': {('user', 'date_local')},
            },
        ),
    ]
