# Generated by Django 5.2.5 on 2025-08-15 14:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_worksettings_office_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='worksettings',
            name='friday_end_time',
            field=models.TimeField(default=datetime.time(13, 0), verbose_name='Friday End Time'),
        ),
        migrations.AddField(
            model_name='worksettings',
            name='friday_grace_minutes',
            field=models.PositiveIntegerField(default=0, verbose_name='Friday Grace Minutes'),
        ),
        migrations.AddField(
            model_name='worksettings',
            name='friday_required_minutes',
            field=models.PositiveIntegerField(default=240, verbose_name='Friday Required Minutes'),
        ),
        migrations.AddField(
            model_name='worksettings',
            name='friday_start_time',
            field=models.TimeField(default=datetime.time(9, 0), verbose_name='Friday Start Time'),
        ),
    ]
