# Generated by Django 5.2.5 on 2025-08-16 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_attendance_correction'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancecorrection',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='corrections/', verbose_name='Surat Pendukung'),
        ),
    ]
