# Generated by Django 5.0.2 on 2025-08-21 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_attendance_overtime_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='fullname',
            field=models.TextField(
                blank=True,
                help_text='Full name of the employee',
                null=True,
                verbose_name='Full Name'
            ),
        ),
    ]
