# Generated by Django 5.0.2 on 2025-08-22 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_add_fullname_to_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='worksettings',
            name='overtime_threshold_minutes',
            field=models.PositiveIntegerField(default=60, help_text='Minimum extra minutes before overtime starts counting (e.g., 60 = 1 hour buffer)', verbose_name='Overtime Threshold (Minutes)'),
        ),
    ]
