# Generated by Django 5.0.2 on 2025-08-23 01:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_attendance_ip_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='overtimerequest',
            name='final_approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Final Approved At'),
        ),
        migrations.AddField(
            model_name='overtimerequest',
            name='final_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='final_approved_overtime_requests', to=settings.AUTH_USER_MODEL, verbose_name='Final Approved By'),
        ),
        migrations.AddField(
            model_name='overtimerequest',
            name='level1_approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Level 1 Approved At'),
        ),
        migrations.AddField(
            model_name='overtimerequest',
            name='level1_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='level1_approved_overtime_requests', to=settings.AUTH_USER_MODEL, verbose_name='Level 1 Approved By'),
        ),
        migrations.AddField(
            model_name='position',
            name='approval_level',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Division Level'), (2, 'Organization Level')], default=1, help_text='1 = Division-level approval, 2 = Organization-level (final) approval', verbose_name='Approval Level'),
        ),
        migrations.AddField(
            model_name='position',
            name='can_approve_overtime_org_wide',
            field=models.BooleanField(default=False, help_text='If true, supervisors with this position can approve overtime requests from all divisions (final approval)', verbose_name='Can Approve Overtime Organization-Wide'),
        ),
        migrations.AlterField(
            model_name='overtimerequest',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Approved At (Legacy)'),
        ),
        migrations.AlterField(
            model_name='overtimerequest',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_overtime_requests', to=settings.AUTH_USER_MODEL, verbose_name='Approved By (Legacy)'),
        ),
        migrations.AlterField(
            model_name='overtimerequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('level1_approved', 'Level 1 Approved (Division)'), ('approved', 'Final Approved'), ('rejected', 'Rejected')], default='pending', max_length=20, verbose_name='Status'),
        ),
    ]
