# Generated by Django 5.0.2 on 2025-08-24 02:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_add_2level_approval_system'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OvertimeExportHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('export_period', models.CharField(help_text='Format: YYYY-MM (e.g., 2024-01)', max_length=7, verbose_name='Export Period')),
                ('export_type', models.CharField(default='monthly_docx', max_length=20, verbose_name='Export Type')),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('level1_approved', 'Level 1 Approved'), ('approved', 'Final Approved'), ('rejected', 'Rejected'), ('exported', 'Successfully Exported'), ('failed', 'Export Failed')], default='pending', max_length=20, verbose_name='Status')),
                ('level1_approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Level 1 Approved At')),
                ('final_approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Final Approved At')),
                ('rejection_reason', models.TextField(blank=True, null=True, verbose_name='Rejection Reason')),
                ('exported_file_path', models.CharField(blank=True, max_length=500, null=True, verbose_name='Exported File Path')),
                ('export_metadata', models.JSONField(blank=True, help_text='Additional export information (file size, record count, etc.)', null=True, verbose_name='Export Metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exported_at', models.DateTimeField(blank=True, null=True, verbose_name='Exported At')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overtime_exports', to='api.employee', verbose_name='Employee')),
                ('final_approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='final_approved_exports', to=settings.AUTH_USER_MODEL, verbose_name='Final Approved By')),
                ('level1_approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='level1_approved_exports', to=settings.AUTH_USER_MODEL, verbose_name='Level 1 Approved By')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overtime_exports', to=settings.AUTH_USER_MODEL, verbose_name='User Requesting Export')),
            ],
            options={
                'verbose_name': 'Overtime Export History',
                'verbose_name_plural': 'Overtime Export Histories',
                'ordering': ['-created_at'],
                'unique_together': {('employee', 'export_period', 'export_type')},
            },
        ),
    ]
