# Generated by Django 5.0.2 on 2025-08-24 07:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_overtimeexporthistory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlySummaryRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_period', models.CharField(help_text='Format: YYYY-MM (e.g., 2024-01)', max_length=7, verbose_name='Periode Laporan')),
                ('report_type', models.CharField(choices=[('monthly_summary', 'Rekap Bulanan'), ('attendance_summary', 'Rekap Absensi'), ('overtime_summary', 'Rekap Lembur'), ('custom_report', 'Laporan Kustom')], default='monthly_summary', max_length=20, verbose_name='Jenis Laporan')),
                ('request_title', models.CharField(blank=True, help_text="Judul laporan yang diminta (e.g., 'Rekap Absensi Januari 2024')", max_length=200, null=True, verbose_name='Judul Laporan')),
                ('request_description', models.TextField(blank=True, help_text='Deskripsi detail laporan yang diminta', null=True, verbose_name='Deskripsi Laporan')),
                ('include_attendance', models.BooleanField(default=True, help_text='Apakah data absensi harian dimasukkan dalam rekap', verbose_name='Include Attendance Data')),
                ('include_overtime', models.BooleanField(default=True, help_text='Apakah data lembur dimasukkan dalam rekap', verbose_name='Include Overtime Data')),
                ('include_corrections', models.BooleanField(default=False, help_text='Apakah data perbaikan absensi dimasukkan dalam rekap', verbose_name='Include Corrections Data')),
                ('include_summary_stats', models.BooleanField(default=True, help_text='Apakah statistik ringkasan dimasukkan dalam rekap', verbose_name='Include Summary Statistics')),
                ('priority', models.CharField(choices=[('low', 'Rendah'), ('medium', 'Sedang'), ('high', 'Tinggi'), ('urgent', 'Urgent')], default='medium', max_length=20, verbose_name='Prioritas')),
                ('expected_completion_date', models.DateField(blank=True, help_text='Tanggal target penyelesaian laporan', null=True, verbose_name='Tanggal Target Selesai')),
                ('status', models.CharField(choices=[('pending', 'Menunggu Approval'), ('level1_approved', 'Level 1 Disetujui'), ('approved', 'Final Disetujui'), ('rejected', 'Ditolak'), ('completed', 'Selesai'), ('cancelled', 'Dibatalkan')], default='pending', max_length=20, verbose_name='Status')),
                ('level1_approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Level 1 Disetujui Pada')),
                ('final_approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Final Disetujui Pada')),
                ('rejection_reason', models.TextField(blank=True, null=True, verbose_name='Alasan Penolakan')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Selesai Pada')),
                ('completion_notes', models.TextField(blank=True, null=True, verbose_name='Catatan Penyelesaian')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overtime_exports', to='api.employee', verbose_name='Employee')),
                ('final_approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='final_approved_summary_requests', to=settings.AUTH_USER_MODEL, verbose_name='Final Disetujui Oleh')),
                ('level1_approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='level1_approved_summary_requests', to=settings.AUTH_USER_MODEL, verbose_name='Level 1 Disetujui Oleh')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overtime_exports', to=settings.AUTH_USER_MODEL, verbose_name='User Requesting Export')),
            ],
            options={
                'verbose_name': 'Pengajuan Rekap Bulanan',
                'verbose_name_plural': 'Pengajuan Rekap Bulanan',
                'ordering': ['-created_at'],
                'unique_together': {('employee', 'request_period', 'report_type')},
            },
        ),
        migrations.DeleteModel(
            name='OvertimeExportHistory',
        ),
    ]
