# Generated by Django 5.0.2 on 2025-08-28 06:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_add_monthly_summary_request_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='worksettings',
            name='earliest_check_in_enabled',
            field=models.BooleanField(default=True, help_text='Whether to enforce earliest check-in time restriction', verbose_name='Enable Early Check-in Restriction'),
        ),
        migrations.AddField(
            model_name='worksettings',
            name='earliest_check_in_time',
            field=models.TimeField(default=datetime.time(6, 0), help_text='Earliest time employees can check in (e.g., 06:00)', verbose_name='Earliest Check-in Time'),
        ),
    ]
