# Generated by Django 5.0.2 on 2025-08-29 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_alter_grouppermission_permission_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='approval_level',
            field=models.PositiveSmallIntegerField(choices=[(0, 'No Approval'), (1, 'Division Level'), (2, 'Organization Level')], default=1, help_text='0 = No approval permission, 1 = Division-level approval, 2 = Organization-level (final) approval', verbose_name='Approval Level'),
        ),
    ]
