# Generated by Django 5.0.2 on 2025-08-30 03:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_add_level_0_approval'),
    ]

    operations = [
        migrations.AddField(
            model_name='worksettings',
            name='earliest_check_out_enabled',
            field=models.BooleanField(default=True, help_text='Whether to enforce earliest check-out time restriction', verbose_name='Enable Early Check-out Restriction'),
        ),
        migrations.AddField(
            model_name='worksettings',
            name='earliest_check_out_time',
            field=models.TimeField(default=datetime.time(17, 0), help_text='Earliest time employees can check out (e.g., 17:00)', verbose_name='Earliest Check-out Time'),
        ),
    ]
