# Generated by Django 5.0.2 on 2025-08-30 03:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_add_earliest_check_out_restriction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worksettings',
            name='earliest_check_out_enabled',
        ),
        migrations.RemoveField(
            model_name='worksettings',
            name='earliest_check_out_time',
        ),
        migrations.AddField(
            model_name='worksettings',
            name='latest_check_out_enabled',
            field=models.BooleanField(default=True, help_text='Whether to enforce latest check-out time restriction', verbose_name='Enable Latest Check-out Restriction'),
        ),
        migrations.AddField(
            model_name='worksettings',
            name='latest_check_out_time',
            field=models.TimeField(default=datetime.time(22, 0), help_text='Latest time employees can check out (e.g., 22:00)', verbose_name='Latest Check-out Time'),
        ),
    ]
