# Generated by Django 5.0.2 on 2025-09-01 04:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_change_earliest_to_latest_check_out'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='overtimerequest',
            name='final_rejected_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Final Rejected At'),
        ),
        migrations.AddField(
            model_name='overtimerequest',
            name='final_rejected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='final_rejected_overtime_requests', to=settings.AUTH_USER_MODEL, verbose_name='Final Rejected By'),
        ),
        migrations.AddField(
            model_name='overtimerequest',
            name='level1_rejected_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Level 1 Rejected At'),
        ),
        migrations.AddField(
            model_name='overtimerequest',
            name='level1_rejected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='level1_rejected_overtime_requests', to=settings.AUTH_USER_MODEL, verbose_name='Level 1 Rejected By'),
        ),
    ]
