# Generated by Django 5.0.2 on 2025-09-01 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_add_rejection_fields_to_overtime_request'),
    ]

    operations = [
        migrations.CreateModel(
            name='OvertimeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docx_file', models.FileField(upload_to='overtime_docx/', verbose_name='DOCX File')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='overtime_pdf/', verbose_name='PDF File')),
                ('document_type', models.CharField(choices=[('individual', 'Individual Request'), ('monthly', 'Monthly Summary')], default='individual', max_length=20, verbose_name='Document Type')),
                ('status', models.CharField(choices=[('generated', 'Generated'), ('converted', 'Converted to PDF'), ('downloaded', 'Downloaded'), ('error', 'Error')], default='generated', max_length=20, verbose_name='Status')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Error Message')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('converted_at', models.DateTimeField(blank=True, null=True)),
                ('downloaded_at', models.DateTimeField(blank=True, null=True)),
                ('overtime_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='api.overtimerequest')),
            ],
            options={
                'verbose_name': 'Overtime Document',
                'verbose_name_plural': 'Overtime Documents',
                'ordering': ['-created_at'],
            },
        ),
    ]
