# Generated by Django 5.0.2 on 2025-09-02 02:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_overtimedocument'),
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.BooleanField(default=False, help_text='Mark this as the primary role for the employee', verbose_name='Primary Role')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this role assignment is active', verbose_name='Is Active')),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_roles', to=settings.AUTH_USER_MODEL, verbose_name='Assigned By')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_roles', to='api.employee', verbose_name='Employee')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_roles', to='auth.group', verbose_name='Role/Group')),
            ],
            options={
                'verbose_name': 'Employee Role',
                'verbose_name_plural': 'Employee Roles',
                'ordering': ['-is_primary', 'group__name'],
                'unique_together': {('employee', 'group')},
            },
        ),
        migrations.DeleteModel(
            name='OvertimeDocument',
        ),
    ]
