# Generated by Django 5.0.2 on 2025-09-05 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_overtimedocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='overtimerequest',
            name='docx_document',
            field=models.OneToOneField(blank=True, help_text='Reference to the generated DOCX document', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='overtime_request_ref', to='api.overtimedocument', verbose_name='Generated DOCX Document'),
        ),
        migrations.AlterField(
            model_name='overtimedocument',
            name='docx_file',
            field=models.FileField(blank=True, null=True, upload_to='overtime_docx/', verbose_name='DOCX File'),
        ),
        migrations.AlterField(
            model_name='overtimedocument',
            name='overtime_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='api.overtimerequest', verbose_name='Overtime Request'),
        ),
        migrations.AlterUniqueTogether(
            name='overtimedocument',
            unique_together={('overtime_request', 'document_type')},
        ),
    ]
