# Generated by Django 5.0.2 on 2025-09-06 11:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_add_docx_document_field'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='grouppermission',
            name='permission_type',
            field=models.CharField(choices=[('attendance', 'Attendance Management'), ('overtime', 'Overtime Management'), ('employee', 'Employee Management'), ('division', 'Division Management'), ('position', 'Position Management'), ('settings', 'System Settings'), ('reports', 'Reports & Analytics'), ('admin', 'Admin Functions'), ('session', 'Session Management'), ('logentry', 'Log Entry Management'), ('contenttype', 'Content Type Management'), ('permission', 'Permission Management'), ('group', 'Group Management'), ('user', 'User Management'), ('holiday', 'Holiday Management'), ('worksettings', 'Work Settings Management'), ('overtimesummaryrequest', 'Overtime Summary Request Management'), ('overtimerequest', 'Overtime Request Management'), ('overtimeexporthistory', 'Overtime Export History Management'), ('attendancecorrection', 'Attendance Correction Management'), ('grouppermission', 'Group Permission Management'), ('grouppermissiontemplate', 'Group Permission Template Management'), ('generatedreport', 'Generated Report Management'), ('reportaccesslog', 'Report Access Log Management'), ('reportschedule', 'Report Schedule Management'), ('reporttemplate', 'Report Template Management')], max_length=30, verbose_name='Permission Type'),
        ),
        migrations.CreateModel(
            name='OvertimeSummaryRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_period', models.CharField(help_text='Format: YYYY-MM (e.g., 2024-01)', max_length=7, verbose_name='Periode Laporan')),
                ('request_title', models.CharField(blank=True, help_text="Judul laporan rekap lembur (e.g., 'Rekap Lembur Januari 2024')", max_length=200, null=True, verbose_name='Judul Laporan Lembur')),
                ('request_description', models.TextField(blank=True, help_text='Deskripsi detail pengajuan rekap lembur', null=True, verbose_name='Deskripsi Pengajuan Lembur')),
                ('include_overtime_details', models.BooleanField(default=True, help_text='Apakah detail lembur per hari dimasukkan dalam rekap', verbose_name='Include Overtime Details')),
                ('include_overtime_summary', models.BooleanField(default=True, help_text='Apakah ringkasan statistik lembur dimasukkan dalam rekap', verbose_name='Include Overtime Summary')),
                ('include_approver_info', models.BooleanField(default=True, help_text='Apakah informasi approver dimasukkan dalam rekap', verbose_name='Include Approver Information')),
                ('status', models.CharField(choices=[('pending', 'Menunggu Approval'), ('level1_approved', 'Level 1 Disetujui'), ('approved', 'Final Disetujui'), ('rejected', 'Ditolak'), ('completed', 'Selesai'), ('cancelled', 'Dibatalkan')], default='pending', max_length=20, verbose_name='Status')),
                ('level1_approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Level 1 Disetujui Pada')),
                ('final_approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Final Disetujui Pada')),
                ('rejection_reason', models.TextField(blank=True, null=True, verbose_name='Alasan Penolakan')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Selesai Pada')),
                ('completion_notes', models.TextField(blank=True, null=True, verbose_name='Catatan Penyelesaian')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overtime_summary_requests', to='api.employee', verbose_name='Employee')),
                ('final_approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='final_approved_overtime_summary_requests', to=settings.AUTH_USER_MODEL, verbose_name='Final Disetujui Oleh')),
                ('level1_approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='level1_approved_overtime_summary_requests', to=settings.AUTH_USER_MODEL, verbose_name='Level 1 Disetujui Oleh')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overtime_summary_requests', to=settings.AUTH_USER_MODEL, verbose_name='User Requesting Export')),
            ],
            options={
                'verbose_name': 'Pengajuan Rekap Lembur Bulanan',
                'verbose_name_plural': 'Pengajuan Rekap Lembur Bulanan',
                'ordering': ['-created_at'],
                'unique_together': {('employee', 'request_period')},
            },
        ),
        migrations.DeleteModel(
            name='MonthlySummaryRequest',
        ),
    ]
