# Generated by Django 5.0.2 on 2025-09-03 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_add_employee_role_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nama role (e.g., admin, supervisor, pegawai)', max_length=50, unique=True, verbose_name='Role Name')),
                ('display_name', models.CharField(help_text='Nama yang ditampilkan di UI (e.g., Administrator, Supervisor)', max_length=100, verbose_name='Display Name')),
                ('role_type', models.CharField(choices=[('primary', 'Primary Role'), ('additional', 'Additional Role'), ('legacy', 'Legacy Role')], default='additional', help_text='Tipe role: primary (wajib), additional (opsional), legacy (backward compatibility)', max_length=20, verbose_name='Role Type')),
                ('approval_level', models.PositiveSmallIntegerField(default=0, help_text='Level approval: 0=Basic, 1=Division, 2=Organization', verbose_name='Approval Level')),
                ('group', models.CharField(blank=True, help_text='Grup untuk pengelompokan di UI (e.g., Primary, Diplomatic, Support)', max_length=50, null=True, verbose_name='UI Group')),
                ('description', models.TextField(blank=True, help_text='Deskripsi role dan fungsinya', null=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, help_text='Apakah role ini aktif dan dapat digunakan', verbose_name='Is Active')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Urutan tampilan di UI', verbose_name='Sort Order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Role Configuration',
                'verbose_name_plural': 'Role Configurations',
                'ordering': ['sort_order', 'name'],
            },
        ),
    ]
