# Generated by Django 5.0.2 on 2025-09-06 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_rename_monthly_to_overtime_summary_request'),
    ]

    operations = [
        migrations.CreateModel(
            name='OvertimeSummaryDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docx_file', models.FileField(blank=True, null=True, upload_to='overtime_summary_docx/', verbose_name='DOCX File')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='overtime_summary_pdf/', verbose_name='PDF File')),
                ('document_type', models.CharField(choices=[('monthly_summary', 'Monthly Summary'), ('monthly_export', 'Monthly Export')], default='monthly_summary', max_length=20, verbose_name='Document Type')),
                ('status', models.CharField(choices=[('generated', 'Generated'), ('converted', 'Converted to PDF'), ('downloaded', 'Downloaded'), ('error', 'Error')], default='generated', max_length=20, verbose_name='Status')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Error Message')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('converted_at', models.DateTimeField(blank=True, null=True)),
                ('downloaded_at', models.DateTimeField(blank=True, null=True)),
                ('overtime_summary_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='api.overtimesummaryrequest', verbose_name='Overtime Summary Request')),
            ],
            options={
                'verbose_name': 'Overtime Summary Document',
                'verbose_name_plural': 'Overtime Summary Documents',
                'ordering': ['-created_at'],
                'unique_together': {('overtime_summary_request', 'document_type')},
            },
        ),
        migrations.AddField(
            model_name='overtimesummaryrequest',
            name='docx_document',
            field=models.OneToOneField(blank=True, help_text='Reference to the generated DOCX document', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='summary_request_ref', to='api.overtimesummarydocument', verbose_name='Generated DOCX Document'),
        ),
    ]
