# Generated by Django 5.0.2 on 2025-09-03 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_add_role_configuration_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roleconfiguration',
            name='approval_level',
            field=models.PositiveSmallIntegerField(choices=[(0, 'No Approval'), (1, 'Division Level'), (2, 'Organization Level (KJRI)')], default=0, help_text='0 = Tidak ada akses approval, 1 = Approval se-divisi, 2 = Approval se-KJRI (organization-wide)', verbose_name='Approval Level'),
        ),
    ]
