# Generated by Django 5.0.2 on 2025-09-03 06:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_update_role_configuration_approval_level_choices'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # RoleConfiguration model has been removed from models.py
        # and table has been manually deleted
        migrations.AlterModelOptions(
            name='employeerole',
            options={'ordering': ['-is_primary', 'role__name'], 'verbose_name': 'Employee Role Assignment', 'verbose_name_plural': 'Employee Role Assignments'},
        ),
        # updated_at field already exists
        migrations.AlterField(
            model_name='employeerole',
            name='assigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='role_assignments', to=settings.AUTH_USER_MODEL, verbose_name='Assigned By'),
        ),
        migrations.AlterField(
            model_name='employeerole',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='api.employee', verbose_name='Employee'),
        ),
        # role field already exists and unique constraint is already set
        migrations.RemoveField(
            model_name='employeerole',
            name='group',
        ),
    ]
