# Generated by Django 5.0.2 on 2025-09-22 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_add_overtime_summary_document'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='grouppermission',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='grouppermission',
            name='group',
        ),
        migrations.DeleteModel(
            name='GroupPermissionTemplate',
        ),
        migrations.AlterUniqueTogether(
            name='overtimedocument',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='overtimedocument',
            name='overtime_request',
        ),
        migrations.RemoveField(
            model_name='overtimerequest',
            name='docx_document',
        ),
        migrations.RemoveField(
            model_name='overtimerequest',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='overtimerequest',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='overtimerequest',
            name='final_approved_by',
        ),
        migrations.RemoveField(
            model_name='overtimerequest',
            name='final_rejected_by',
        ),
        migrations.RemoveField(
            model_name='overtimerequest',
            name='level1_approved_by',
        ),
        migrations.RemoveField(
            model_name='overtimerequest',
            name='level1_rejected_by',
        ),
        migrations.RemoveField(
            model_name='overtimerequest',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='overtimesummarydocument',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='overtimesummarydocument',
            name='overtime_summary_request',
        ),
        migrations.RemoveField(
            model_name='overtimesummaryrequest',
            name='docx_document',
        ),
        migrations.AlterUniqueTogether(
            name='overtimesummaryrequest',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='overtimesummaryrequest',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='overtimesummaryrequest',
            name='final_approved_by',
        ),
        migrations.RemoveField(
            model_name='overtimesummaryrequest',
            name='level1_approved_by',
        ),
        migrations.RemoveField(
            model_name='overtimesummaryrequest',
            name='user',
        ),
        migrations.AlterField(
            model_name='attendance',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='api.employee'),
        ),
        migrations.DeleteModel(
            name='GroupPermission',
        ),
        migrations.DeleteModel(
            name='OvertimeDocument',
        ),
        migrations.DeleteModel(
            name='OvertimeRequest',
        ),
        migrations.DeleteModel(
            name='OvertimeSummaryDocument',
        ),
        migrations.DeleteModel(
            name='OvertimeSummaryRequest',
        ),
    ]
