# Generated by Django 5.0.2 on 2025-09-03 08:50
"""
Migration marker for completed Role System migration.

This migration serves as a marker to indicate that the unified Role System
has been successfully implemented and migrated. All necessary database changes
have been applied and the system is ready for use.

Key changes completed:
- Created Role model to replace RoleConfiguration
- Updated EmployeeRole model to use Role instead of Group
- Migrated all existing data from old system to new system
- Updated all views, permissions, and utilities to use new Role system
- Removed old position-based approval logic (marked as deprecated)

This is an empty migration that marks the completion of the migration process.
"""

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_add_updated_at_to_employeerole'),
    ]

    operations = [
        # Empty migration - Role System migration is complete
        # All database changes have been applied successfully
    ]
