# Generated by Django 5.0.2 on 2025-09-03 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_role_system_migrated'),
    ]

    operations = [
    ]
