# Generated by Django 5.0.2 on 2025-09-03 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_auto_20250903_0911'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Unique role identifier (e.g., 'admin', 'supervisor', 'pegawai')", max_length=50, unique=True, verbose_name='Role Name')),
                ('display_name', models.CharField(help_text="Display name for UI (e.g., 'Administrator', 'Supervisor')", max_length=100, verbose_name='Display Name')),
                ('description', models.TextField(blank=True, help_text='Description of role responsibilities', null=True, verbose_name='Description')),
                ('approval_level', models.PositiveSmallIntegerField(choices=[(0, 'No Approval'), (1, 'Division Level'), (2, 'Organization Level')], default=0, help_text='Approval level for overtime and other requests', verbose_name='Approval Level')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this role is active and can be assigned', verbose_name='Is Active')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Sort order for UI display', verbose_name='Sort Order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Role',
                'verbose_name_plural': 'Roles',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.DeleteModel(
            name='RoleConfiguration',
        ),
        migrations.AddField(
            model_name='employeerole',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='approval_level',
            field=models.PositiveSmallIntegerField(choices=[(0, 'No Approval'), (1, 'Division Level'), (2, 'Organization Level')], default=1, help_text='[DEPRECATED] This field is no longer used. Approval permissions are now handled by Role model.', verbose_name='[DEPRECATED] Approval Level'),
        ),
        migrations.AlterField(
            model_name='position',
            name='can_approve_overtime_org_wide',
            field=models.BooleanField(default=False, help_text='[DEPRECATED] This field is no longer used. Approval permissions are now handled by Role model.', verbose_name='[DEPRECATED] Can Approve Overtime Organization-Wide'),
        ),
        migrations.AlterUniqueTogether(
            name='employeerole',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='employeerole',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_assignments', to='api.role', verbose_name='Role'),
        ),
        migrations.AlterUniqueTogether(
            name='employeerole',
            unique_together={('employee', 'role')},
        ),
    ]
