# Generated by Django 5.0.2 on 2025-09-03 09:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_role_delete_roleconfiguration_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancecorrection',
            name='level1_approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Level 1 Approved At'),
        ),
        migrations.AddField(
            model_name='attendancecorrection',
            name='level1_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='level1_approved_corrections', to=settings.AUTH_USER_MODEL, verbose_name='Level 1 Approved By'),
        ),
        migrations.AlterField(
            model_name='attendancecorrection',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('level1_approved', 'Level 1 Approved (Division)'), ('approved', 'Final Approved'), ('rejected', 'Rejected')], default='pending', max_length=16),
        ),
    ]
