# Generated by Django 5.0.2 on 2025-09-04 04:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_add_sequential_approval_to_attendance_correction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendancecorrection',
            name='level1_approved_at',
        ),
        migrations.RemoveField(
            model_name='attendancecorrection',
            name='level1_approved_by',
        ),
        migrations.AddField(
            model_name='employeerole',
            name='deactivated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Deactivated At'),
        ),
        migrations.AddField(
            model_name='employeerole',
            name='deactivated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deactivated_role_assignments', to=settings.AUTH_USER_MODEL, verbose_name='Deactivated By'),
        ),
        migrations.AddField(
            model_name='role',
            name='is_system_role',
            field=models.BooleanField(default=False, help_text='System roles cannot be deleted', verbose_name='System Role'),
        ),
        migrations.AddField(
            model_name='role',
            name='permissions',
            field=models.JSONField(default=dict, help_text="Permissions in format: {'attendance': ['view', 'create'], 'overtime': ['view']}", verbose_name='Role Permissions'),
        ),
        migrations.AlterField(
            model_name='attendancecorrection',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=16),
        ),
        migrations.AlterField(
            model_name='employeerole',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_roles', to='api.employee', verbose_name='Employee'),
        ),
        migrations.AlterField(
            model_name='employeerole',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_assignments', to='api.role', verbose_name='Role'),
        ),
        migrations.AddIndex(
            model_name='employeerole',
            index=models.Index(fields=['employee', 'is_active'], name='api_employe_employe_9909eb_idx'),
        ),
        migrations.AddIndex(
            model_name='employeerole',
            index=models.Index(fields=['role', 'is_active'], name='api_employe_role_id_be9b28_idx'),
        ),
        migrations.AddIndex(
            model_name='employeerole',
            index=models.Index(fields=['is_primary', 'is_active'], name='api_employe_is_prim_6c8909_idx'),
        ),
        migrations.AddIndex(
            model_name='role',
            index=models.Index(fields=['name', 'is_active'], name='api_role_name_d5039a_idx'),
        ),
        migrations.AddIndex(
            model_name='role',
            index=models.Index(fields=['approval_level', 'is_active'], name='api_role_approva_901cb7_idx'),
        ),
    ]
