# Generated by Django 5.0.2 on 2025-09-04 05:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_phase1_role_consolidation'),
    ]

    operations = [
        # Skip role_category - already exists from previous migration

        # Add max users limit per role
        migrations.AddField(
            model_name='role',
            name='max_users',
            field=models.PositiveIntegerField(
                blank=True,
                help_text='Maximum number of users that can be assigned this role (0 = unlimited)',
                null=True,
                verbose_name='Max Users'
            ),
        ),

        # Add role priority for approval hierarchy
        migrations.AddField(
            model_name='role',
            name='role_priority',
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text='Priority level for approval hierarchy (higher = more authority)',
                verbose_name='Role Priority'
            ),
        ),

        # Add audit fields to EmployeeRole
        migrations.AddField(
            model_name='employeerole',
            name='notes',
            field=models.TextField(
                blank=True,
                help_text='Additional notes about this role assignment',
                verbose_name='Notes'
            ),
        ),

        # Add role assignment expiry
        migrations.AddField(
            model_name='employeerole',
            name='expires_at',
            field=models.DateTimeField(
                blank=True,
                help_text='When this role assignment expires (optional)',
                null=True,
                verbose_name='Expires At'
            ),
        ),

        # Skip role_category index - already exists

        migrations.AddIndex(
            model_name='employeerole',
            index=models.Index(fields=['expires_at', 'is_active'], name='api_employe_expires_345678_idx'),
        ),

        migrations.AddIndex(
            model_name='employeerole',
            index=models.Index(fields=['role', 'expires_at'], name='api_employe_role_exp_901234_idx'),
        ),

        # Update existing roles with default priority values
        migrations.RunSQL(
            """
            UPDATE api_role
            SET role_priority = CASE
                WHEN LOWER(name) LIKE '%admin%' THEN 100
                WHEN LOWER(name) LIKE '%supervisor%' OR LOWER(name) LIKE '%spv%' THEN 50
                WHEN LOWER(name) = 'pegawai' THEN 10
                ELSE 0
            END
            WHERE role_priority = 0;
            """,
            reverse_sql=""
        ),
    ]
