# Generated by Django 5.0.2 on 2025-09-04 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_phase1_role_improvements'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='role_category',
            field=models.CharField(
                choices=[
                    ('admin', 'Administrator'),
                    ('supervisor', 'Supervisor'),
                    ('employee', 'Employee'),
                    ('system', 'System Role'),
                ],
                default='employee',
                help_text='Category of the role for better organization',
                max_length=20,
                verbose_name='Role Category'
            ),
        ),

        # Add index for role_category
        migrations.AddIndex(
            model_name='role',
            index=models.Index(fields=['role_category', 'is_active'], name='api_role_role_cat_final_idx'),
        ),

        # Update existing roles with proper categories
        migrations.RunSQL(
            """
            UPDATE api_role
            SET role_category = CASE
                WHEN LOWER(name) LIKE '%admin%' THEN 'admin'
                WHEN LOWER(name) LIKE '%supervisor%' OR LOWER(name) LIKE '%spv%' THEN 'supervisor'
                WHEN LOWER(name) = 'pegawai' THEN 'employee'
                ELSE 'employee'
            END
            WHERE role_category IS NULL OR role_category = '';
            """,
            reverse_sql=""
        ),
    ]
