# Generated by Django 5.0.2 on 2025-09-04 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_phase1_role_improvements'),
    ]

    operations = [
        # Skip index operations - will handle separately if needed
        # Skip role_category - already exists from previous migration
        migrations.AlterField(
            model_name='employeerole',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='api.employee', verbose_name='Employee'),
        ),
        migrations.AlterField(
            model_name='employeerole',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_assignments', to='api.role', verbose_name='Role'),
        ),
    ]
  