# Generated by Django 5.0.2 on 2025-09-04 06:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_fix_model_state'),
    ]

    operations = [
        # Phase 2: Add parent role functionality
        # Skip inherit_permissions - already exists
        # Skip parent_role - manually added to database
        # Skip role_category - already exists from Phase 1
    ]
