# Generated by Django 5.0.2 on 2025-09-04 06:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_phase2_parent_roles'),
    ]

    operations = [
        # Phase 2: Create RoleTemplate model
        migrations.CreateModel(
            name='RoleTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Unique template name', max_length=100, unique=True, verbose_name='Template Name')),
                ('display_name', models.CharField(help_text='Display name for the template', max_length=150, verbose_name='Display Name')),
                ('description', models.TextField(help_text='Description of what this template is for', verbose_name='Description')),
                ('category', models.CharField(choices=[('system', 'System Templates'), ('organizational', 'Organizational Templates'), ('departmental', 'Departmental Templates'), ('custom', 'Custom Templates')], default='custom', help_text='Category of the template', max_length=20, verbose_name='Category')),
                ('base_role_category', models.CharField(choices=[('admin', 'Administrator'), ('supervisor', 'Supervisor'), ('employee', 'Employee'), ('system', 'System Role')], default='employee', help_text='Default role category for roles created from this template', max_length=20, verbose_name='Base Role Category')),
                ('base_approval_level', models.PositiveSmallIntegerField(choices=[(0, 'No Approval'), (1, 'Division Level'), (2, 'Organization Level')], default=0, help_text='Default approval level', verbose_name='Base Approval Level')),
                ('base_permissions', models.JSONField(default=dict, help_text="Default permissions in format: {'attendance': ['view', 'create'], 'overtime': ['view']}", verbose_name='Base Permissions')),
                ('base_max_users', models.PositiveIntegerField(blank=True, help_text='Default maximum users (null = unlimited)', null=True, verbose_name='Base Max Users')),
                ('base_role_priority', models.PositiveSmallIntegerField(default=0, help_text='Default role priority', verbose_name='Base Role Priority')),
                ('is_system_template', models.BooleanField(default=False, help_text='System templates cannot be deleted', verbose_name='System Template')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this template is active and available for use', verbose_name='Is Active')),
                ('usage_count', models.PositiveIntegerField(default=0, help_text='Number of times this template has been used to create roles', verbose_name='Usage Count')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Role Template',
                'verbose_name_plural': 'Role Templates',
                'ordering': ['category', 'name'],
            },
        ),
        # Skip other operations - already handled in previous migrations
    ]
