# Generated by Django 5.0.2 on 2025-09-04 06:20

from django.db import migrations


def create_default_role_templates(apps, schema_editor):
    """Create default role templates for common use cases"""
    RoleTemplate = apps.get_model('api', 'RoleTemplate')

    # System Templates
    RoleTemplate.objects.create(
        name='system_admin_template',
        display_name='System Administrator',
        description='Full system access template for system administrators',
        category='system',
        base_role_category='admin',
        base_approval_level=2,  # Organization Level
        base_permissions={
            'attendance': ['view', 'create', 'edit', 'delete', 'approve'],
            'overtime': ['view', 'create', 'edit', 'delete', 'approve'],
            'employee': ['view', 'create', 'edit', 'delete'],
            'division': ['view', 'create', 'edit', 'delete'],
            'position': ['view', 'create', 'edit', 'delete'],
            'settings': ['view', 'edit'],
            'reports': ['view', 'export'],
            'admin': ['view', 'create', 'edit', 'delete'],
        },
        base_max_users=5,
        base_role_priority=100,
        is_system_template=True,
    )

    # Organizational Templates
    RoleTemplate.objects.create(
        name='org_hr_manager_template',
        display_name='HR Manager',
        description='Human Resources manager with employee and attendance management',
        category='organizational',
        base_role_category='supervisor',
        base_approval_level=2,
        base_permissions={
            'attendance': ['view', 'create', 'edit', 'approve'],
            'overtime': ['view', 'create', 'edit', 'approve'],
            'employee': ['view', 'create', 'edit'],
            'division': ['view', 'create', 'edit'],
            'position': ['view', 'create', 'edit'],
            'reports': ['view', 'export'],
        },
        base_max_users=10,
        base_role_priority=80,
    )

    RoleTemplate.objects.create(
        name='org_supervisor_template',
        display_name='Department Supervisor',
        description='Department supervisor with team management capabilities',
        category='organizational',
        base_role_category='supervisor',
        base_approval_level=1,  # Division Level
        base_permissions={
            'attendance': ['view', 'edit', 'approve'],
            'overtime': ['view', 'edit', 'approve'],
            'employee': ['view', 'edit'],
            'reports': ['view', 'export'],
        },
        base_max_users=50,
        base_role_priority=60,
    )

    # Departmental Templates
    RoleTemplate.objects.create(
        name='dept_team_lead_template',
        display_name='Team Lead',
        description='Team lead with limited supervisory permissions',
        category='departmental',
        base_role_category='supervisor',
        base_approval_level=1,
        base_permissions={
            'attendance': ['view', 'edit'],
            'overtime': ['view', 'edit'],
            'employee': ['view'],
            'reports': ['view'],
        },
        base_max_users=20,
        base_role_priority=40,
    )

    # Employee Templates
    RoleTemplate.objects.create(
        name='employee_basic_template',
        display_name='Basic Employee',
        description='Standard employee with basic attendance permissions',
        category='custom',
        base_role_category='employee',
        base_approval_level=0,
        base_permissions={
            'attendance': ['view', 'create'],
            'overtime': ['view', 'create'],
        },
        base_role_priority=10,
    )

    RoleTemplate.objects.create(
        name='employee_senior_template',
        display_name='Senior Employee',
        description='Senior employee with additional reporting permissions',
        category='custom',
        base_role_category='employee',
        base_approval_level=0,
        base_permissions={
            'attendance': ['view', 'create', 'edit'],
            'overtime': ['view', 'create', 'edit'],
            'reports': ['view'],
        },
        base_max_users=100,
        base_role_priority=20,
    )


def remove_default_role_templates(apps, schema_editor):
    """Remove default role templates"""
    RoleTemplate = apps.get_model('api', 'RoleTemplate')
    RoleTemplate.objects.filter(
        name__in=[
            'system_admin_template',
            'org_hr_manager_template',
            'org_supervisor_template',
            'dept_team_lead_template',
            'employee_basic_template',
            'employee_senior_template',
        ]
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_phase2_role_templates'),
    ]

    operations = [
        migrations.RunPython(
            create_default_role_templates,
            reverse_code=remove_default_role_templates
        ),
    ]
