# Generated by Django 5.0.2 on 2025-09-26 03:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('employees', '0004_add_active_position_switching'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200, verbose_name='Judul')),
                ('content', models.TextField(verbose_name='Isi Notifikasi')),
                ('notification_type', models.CharField(choices=[('announcement', 'Pengumuman'), ('system_alert', 'Peringatan Sistem'), ('attendance_reminder', 'Pengingat Absensi'), ('policy_update', 'Update Kebijakan'), ('maintenance', 'Pemeliharaan Sistem'), ('division_notice', 'Pemberitahuan Divisi'), ('organization_wide', 'Pemberitahuan Organisasi')], default='announcement', max_length=20, verbose_name='Tipe Notifikasi')),
                ('priority', models.CharField(choices=[('low', 'Rendah'), ('medium', 'Sedang'), ('high', 'Tinggi'), ('urgent', 'Mendesak')], default='medium', max_length=10, verbose_name='Prioritas')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Dipublikasikan'), ('archived', 'Diarsipkan'), ('expired', 'Kedaluwarsa')], default='draft', max_length=10, verbose_name='Status')),
                ('expiry_mode', models.CharField(choices=[('manual', 'Manual (Admin Archive)'), ('time_based', 'Berdasarkan Waktu'), ('read_based', 'Setelah Semua User Membaca'), ('hybrid', 'Waktu atau Setelah Dibaca (mana yang lebih dulu)')], default='time_based', help_text='Cara notifikasi akan expired', max_length=15, verbose_name='Mode Kedaluwarsa')),
                ('expires_at', models.DateTimeField(blank=True, help_text='Auto-expire pada waktu tertentu (untuk time_based/hybrid)', null=True, verbose_name='Kedaluwarsa Pada')),
                ('expire_after_hours', models.PositiveIntegerField(default=24, help_text='Expire setelah berapa jam (default: 24 jam = 1 hari)', verbose_name='Kedaluwarsa Setelah (Jam)')),
                ('expire_when_all_read', models.BooleanField(default=False, help_text='Expire ketika semua target user sudah membaca (untuk read_based/hybrid)', verbose_name='Kedaluwarsa Setelah Semua Membaca')),
                ('publish_at', models.DateTimeField(blank=True, help_text='Schedule publication', null=True, verbose_name='Publikasi Pada')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='notifications/', verbose_name='Lampiran')),
                ('is_sticky', models.BooleanField(default=False, help_text='Always show at top', verbose_name='Sticky')),
                ('requires_acknowledgment', models.BooleanField(default=False, help_text='User must acknowledge', verbose_name='Perlu Konfirmasi')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_notifications', to=settings.AUTH_USER_MODEL, verbose_name='Dibuat Oleh')),
                ('target_divisions', models.ManyToManyField(blank=True, help_text='Target divisions', to='employees.division', verbose_name='Target Divisi')),
                ('target_groups', models.ManyToManyField(blank=True, help_text='Target groups', to='auth.group', verbose_name='Target Groups')),
                ('target_positions', models.ManyToManyField(blank=True, help_text='Target positions', to='employees.position', verbose_name='Target Posisi')),
                ('target_specific_users', models.ManyToManyField(blank=True, help_text='Specific users', to=settings.AUTH_USER_MODEL, verbose_name='Target User Spesifik')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-is_sticky', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationRead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Dibaca Pada')),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True, verbose_name='Dikonfirmasi Pada')),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reads', to='notifications.notification', verbose_name='Notification')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_reads', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Notification Read',
                'verbose_name_plural': 'Notification Reads',
            },
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['status', 'expires_at'], name='notificatio_status_3e9607_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['created_at'], name='notificatio_created_46ad24_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['notification_type'], name='notificatio_notific_f2898f_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationread',
            index=models.Index(fields=['user', 'read_at'], name='notificatio_user_id_2146c3_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationread',
            index=models.Index(fields=['notification', 'read_at'], name='notificatio_notific_7b6f2a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='notificationread',
            unique_together={('notification', 'user')},
        ),
    ]
