# Generated by Django 5.0.2 on 2025-08-25 23:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attendance', '0001_initial'),
        ('employees', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceCorrection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('correction_type', models.CharField(choices=[('check_in', 'Check-in Time'), ('check_out', 'Check-out Time'), ('both', 'Both Check-in and Check-out'), ('note', 'Add/Update Note')], max_length=20, verbose_name='Type of Correction')),
                ('requested_check_in', models.DateTimeField(blank=True, null=True, verbose_name='Requested Check-in Time')),
                ('requested_check_out', models.DateTimeField(blank=True, null=True, verbose_name='Requested Check-out Time')),
                ('requested_note', models.TextField(blank=True, null=True, verbose_name='Requested Note')),
                ('reason', models.TextField(help_text='Explain why this correction is needed', verbose_name='Reason for Correction')),
                ('supporting_document', models.FileField(blank=True, null=True, upload_to='corrections/', verbose_name='Supporting Document')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20, verbose_name='Status')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Approved At')),
                ('rejection_reason', models.TextField(blank=True, null=True, verbose_name='Rejection Reason')),
                ('requested_at', models.DateTimeField(auto_now_add=True, verbose_name='Requested At')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_corrections', to=settings.AUTH_USER_MODEL, verbose_name='Approved By')),
                ('attendance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corrections', to='attendance.attendance', verbose_name='Original Attendance Record')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='correction_requests', to='employees.employee')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correction_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Attendance Correction',
                'verbose_name_plural': 'Attendance Corrections',
                'ordering': ['-requested_at'],
            },
        ),
    ]
