# Generated by Django 5.0.2 on 2025-09-14 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
        ('corrections', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancecorrection',
            name='date_local',
            field=models.DateField(blank=True, help_text='Required for manual corrections when no attendance record exists', null=True, verbose_name='Date for Manual Correction'),
        ),
        migrations.AlterField(
            model_name='attendancecorrection',
            name='attendance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='corrections', to='attendance.attendance', verbose_name='Original Attendance Record'),
        ),
    ]
