# Generated by Django 5.0.2 on 2025-09-22 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corrections', '0002_attendancecorrection_date_local_and_more'),
        ('employees', '0004_add_active_position_switching'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancecorrection',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='correction_requests', to='employees.employee'),
        ),
    ]
