# Generated by Django 5.0.2 on 2025-08-25 23:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attendance', '0001_initial'),
        ('employees', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OvertimeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('request_type', models.CharField(choices=[('regular', 'Regular Overtime'), ('holiday', 'Holiday Overtime'), ('weekend', 'Weekend Overtime'), ('emergency', 'Emergency Overtime')], default='regular', max_length=20, verbose_name='Type of Overtime')),
                ('date', models.DateField(verbose_name='Overtime Date')),
                ('start_time', models.TimeField(verbose_name='Start Time')),
                ('end_time', models.TimeField(verbose_name='End Time')),
                ('total_hours', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Total Hours')),
                ('purpose', models.TextField(help_text='Explain why overtime is needed', verbose_name='Purpose of Overtime')),
                ('work_description', models.TextField(help_text='Describe the work to be done during overtime', verbose_name='Work Description')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20, verbose_name='Status')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Approved At')),
                ('rejection_reason', models.TextField(blank=True, null=True, verbose_name='Rejection Reason')),
                ('hourly_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Hourly Rate')),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Total Amount')),
                ('requested_at', models.DateTimeField(auto_now_add=True, verbose_name='Requested At')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_overtime_request_records', to=settings.AUTH_USER_MODEL, verbose_name='Approved By')),
                ('attendance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overtime_requests', to='attendance.attendance', verbose_name='Related Attendance Record')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='overtime_requests', to='employees.employee')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overtime_request_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Overtime Request',
                'verbose_name_plural': 'Overtime Requests',
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='MonthlySummaryRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('month', models.PositiveIntegerField(verbose_name='Month (1-12)')),
                ('year', models.PositiveIntegerField(verbose_name='Year')),
                ('purpose', models.TextField(help_text='Explain why this monthly summary is needed', verbose_name='Purpose of Request')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20, verbose_name='Status')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Approved At')),
                ('rejection_reason', models.TextField(blank=True, null=True, verbose_name='Rejection Reason')),
                ('requested_at', models.DateTimeField(auto_now_add=True, verbose_name='Requested At')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_monthly_summary_records', to=settings.AUTH_USER_MODEL, verbose_name='Approved By')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monthly_summary_requests', to='employees.employee')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_summary_request_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Monthly Summary Request',
                'verbose_name_plural': 'Monthly Summary Requests',
                'ordering': ['-year', '-month', '-requested_at'],
                'unique_together': {('user', 'month', 'year')},
            },
        ),
    ]
