# Generated by Django 5.0.2 on 2025-09-15 07:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overtime', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='overtimerequest',
            name='final_approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Final Approved At'),
        ),
        migrations.AddField(
            model_name='overtimerequest',
            name='final_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='final_approved_overtime_requests', to=settings.AUTH_USER_MODEL, verbose_name='Final Approved By'),
        ),
        migrations.AddField(
            model_name='overtimerequest',
            name='level1_approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Level 1 Approved At'),
        ),
        migrations.AddField(
            model_name='overtimerequest',
            name='level1_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='level1_approved_overtime_requests', to=settings.AUTH_USER_MODEL, verbose_name='Level 1 Approved By'),
        ),
        migrations.AlterField(
            model_name='overtimerequest',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Approved At (deprecated)'),
        ),
        migrations.AlterField(
            model_name='overtimerequest',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_overtime_request_records', to=settings.AUTH_USER_MODEL, verbose_name='Approved By (deprecated)'),
        ),
        migrations.AlterField(
            model_name='overtimerequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('level1_approved', 'Level 1 Approved'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20, verbose_name='Status'),
        ),
    ]
