# Generated by Django 5.0.2 on 2025-09-15 14:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overtime', '0002_overtimerequest_final_approved_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlysummaryrequest',
            name='level1_approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Level 1 Approved At'),
        ),
        migrations.AddField(
            model_name='monthlysummaryrequest',
            name='level1_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='level1_approved_monthly_summary_records', to=settings.AUTH_USER_MODEL, verbose_name='Level 1 Approved By'),
        ),
        migrations.AlterField(
            model_name='monthlysummaryrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('level1_approved', 'Level 1 Approved'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20, verbose_name='Status'),
        ),
    ]
