# Generated by Django 5.0.2 on 2025-09-22 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_add_active_position_switching'),
        ('overtime', '0003_monthlysummaryrequest_level1_approved_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlysummaryrequest',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='monthly_summary_requests', to='employees.employee'),
        ),
        migrations.AlterField(
            model_name='overtimerequest',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='overtime_requests', to='employees.employee'),
        ),
    ]
