# Generated by Django 5.0.2 on 2025-08-25 16:38

import apps.settings.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(unique=True)),
                ('note', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'Holiday',
                'verbose_name_plural': 'Holidays',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='WorkSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('timezone', models.CharField(default='Asia/Dubai', max_length=64)),
                ('start_time', models.TimeField(default=datetime.time(9, 0))),
                ('end_time', models.TimeField(default=datetime.time(17, 0))),
                ('required_minutes', models.PositiveIntegerField(default=480)),
                ('grace_minutes', models.PositiveIntegerField(default=0)),
                ('workdays', models.JSONField(default=apps.settings.models.WorkSettings._default_workdays)),
                ('friday_start_time', models.TimeField(default=datetime.time(9, 0), verbose_name='Friday Start Time')),
                ('friday_end_time', models.TimeField(default=datetime.time(13, 0), verbose_name='Friday End Time')),
                ('friday_required_minutes', models.PositiveIntegerField(default=240, verbose_name='Friday Required Minutes')),
                ('friday_grace_minutes', models.PositiveIntegerField(default=0, verbose_name='Friday Grace Minutes')),
                ('office_latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('office_longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('office_radius_meters', models.PositiveIntegerField(default=100)),
                ('overtime_rate_workday', models.DecimalField(decimal_places=2, default=0.5, help_text='Multiplier of hourly base wage for overtime on workdays (e.g., 0.50 = 2/4)', max_digits=5, verbose_name='Overtime Rate (Workday)')),
                ('overtime_rate_holiday', models.DecimalField(decimal_places=2, default=0.75, help_text='Multiplier of hourly base wage for overtime on holidays (e.g., 0.75 = 3/4)', max_digits=5, verbose_name='Overtime Rate (Holiday)')),
                ('overtime_threshold_minutes', models.PositiveIntegerField(default=60, help_text='Minimum extra minutes before overtime starts counting (e.g., 60 = 1 hour buffer)', verbose_name='Overtime Threshold (Minutes)')),
            ],
            options={
                'verbose_name': 'Work Settings',
                'verbose_name_plural': 'Work Settings',
            },
        ),
    ]
