# Generated by Django 5.0.2 on 2025-09-13 08:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='worksettings',
            name='earliest_check_in_enabled',
            field=models.BooleanField(default=False, help_text='Enable restriction for earliest check-in time', verbose_name='Enable Earliest Check-in Restriction'),
        ),
        migrations.AddField(
            model_name='worksettings',
            name='earliest_check_in_time',
            field=models.TimeField(default=datetime.time(6, 0), help_text='Earliest time employees can check-in (e.g., 06:00)', verbose_name='Earliest Check-in Time'),
        ),
        migrations.AddField(
            model_name='worksettings',
            name='latest_check_out_enabled',
            field=models.BooleanField(default=False, help_text='Enable restriction for latest check-out time', verbose_name='Enable Latest Check-out Restriction'),
        ),
        migrations.AddField(
            model_name='worksettings',
            name='latest_check_out_time',
            field=models.TimeField(default=datetime.time(22, 0), help_text='Latest time employees can check-out (e.g., 22:00)', verbose_name='Latest Check-out Time'),
        ),
    ]
