# Generated by Django 5.0.2 on 2025-09-14 10:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='worksettings',
            name='earliest_check_in_enabled',
            field=models.BooleanField(default=False, help_text='If enabled, restrict check-in to after specified time', verbose_name='Enable Earliest Check-in'),
        ),
        migrations.AddField(
            model_name='worksettings',
            name='earliest_check_in_time',
            field=models.TimeField(default=datetime.time(6, 0), help_text='Earliest allowed check-in time', verbose_name='Earliest Check-in Time'),
        ),
        migrations.AddField(
            model_name='worksettings',
            name='latest_check_out_enabled',
            field=models.BooleanField(default=False, help_text='If enabled, restrict check-out to before specified time', verbose_name='Enable Latest Check-out'),
        ),
        migrations.AddField(
            model_name='worksettings',
            name='latest_check_out_time',
            field=models.TimeField(default=datetime.time(22, 0), help_text='Latest allowed check-out time', verbose_name='Latest Check-out Time'),
        ),
    ]
