# Generated by Django 5.0.2 on 2025-09-26 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_worksettings_earliest_check_in_enabled_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worksettings',
            name='overtime_rate_holiday',
            field=models.DecimalField(decimal_places=4, default=0.75, help_text='Multiplier of hourly base wage for overtime on holidays (e.g., 0.75 = 3/4)', max_digits=6, verbose_name='Overtime Rate (Holiday)'),
        ),
        migrations.AlterField(
            model_name='worksettings',
            name='overtime_rate_workday',
            field=models.DecimalField(decimal_places=4, default=0.5, help_text='Multiplier of hourly base wage for overtime on workdays (e.g., 0.50 = 2/4)', max_digits=6, verbose_name='Overtime Rate (Workday)'),
        ),
    ]
