# Generated by Django 5.0.2 on 2025-10-03 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_alter_worksettings_overtime_rate_holiday_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='worksettings',
            name='overtime_payment_threshold_hours',
            field=models.DecimalField(decimal_places=2, default=1.0, help_text='Minimum overtime hours before payment starts (e.g., 1.00 = only pay if overtime > 1 hour)', max_digits=4, verbose_name='Overtime Payment Threshold (Hours)'),
        ),
    ]
