# Generated by Django 5.0.2 on 2025-10-03 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0004_worksettings_overtime_payment_threshold_hours'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worksettings',
            name='overtime_payment_threshold_hours',
        ),
        migrations.AddField(
            model_name='worksettings',
            name='overtime_payment_threshold_minutes',
            field=models.PositiveIntegerField(default=60, help_text='Minimum overtime minutes before payment starts (e.g., 60 = only pay if overtime > 60 minutes)', verbose_name='Overtime Payment Threshold (Minutes)'),
        ),
    ]
