# Generated by Django 5.0.2 on 2025-09-15 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupPermissionTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Template Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('permissions', models.JSONField(default=list, help_text="List of permission strings in format: [{'type': 'attendance', 'action': 'view'}]", verbose_name='Permissions List')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Permission Template',
                'verbose_name_plural': 'Permission Templates',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GroupPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission_type', models.CharField(choices=[('attendance', 'Attendance Management'), ('overtime', 'Overtime Management'), ('employee', 'Employee Management'), ('division', 'Division Management'), ('position', 'Position Management'), ('settings', 'System Settings'), ('reports', 'Reports & Analytics'), ('admin', 'Admin Functions'), ('session', 'Session Management'), ('logentry', 'Log Entry Management'), ('contenttype', 'Content Type Management'), ('permission', 'Permission Management'), ('group', 'Group Management'), ('user', 'User Management'), ('holiday', 'Holiday Management'), ('worksettings', 'Work Settings Management'), ('overtimesummaryrequest', 'Overtime Summary Request Management'), ('overtimerequest', 'Overtime Request Management'), ('overtimeexporthistory', 'Overtime Export History Management'), ('attendancecorrection', 'Attendance Correction Management'), ('grouppermission', 'Group Permission Management'), ('grouppermissiontemplate', 'Group Permission Template Management'), ('generatedreport', 'Generated Report Management'), ('reportaccesslog', 'Report Access Log Management'), ('reportschedule', 'Report Schedule Management'), ('reporttemplate', 'Report Template Management')], max_length=30, verbose_name='Permission Type')),
                ('permission_action', models.CharField(choices=[('view', 'View'), ('create', 'Create'), ('edit', 'Edit'), ('delete', 'Delete'), ('approve', 'Approve'), ('reject', 'Reject'), ('export', 'Export'), ('import', 'Import')], max_length=20, verbose_name='Permission Action')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_permissions', to='auth.group', verbose_name='Group')),
            ],
            options={
                'verbose_name': 'Group Permission',
                'verbose_name_plural': 'Group Permissions',
                'ordering': ['group__name', 'permission_type', 'permission_action'],
                'unique_together': {('group', 'permission_type', 'permission_action')},
            },
        ),
    ]
