# Generated by Django 5.0.2 on 2025-10-03 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grouppermission',
            name='permission_type',
            field=models.CharField(choices=[('attendance', 'Attendance Management'), ('overtime', 'Overtime Management'), ('employee', 'Employee Management'), ('division', 'Division Management'), ('position', 'Position Management'), ('settings', 'System Settings'), ('reports', 'Reports & Analytics'), ('admin', 'Admin Functions'), ('session', 'Session Management'), ('logentry', 'Log Entry Management'), ('contenttype', 'Content Type Management'), ('permission', 'Permission Management'), ('group', 'Group Management'), ('user', 'User Management'), ('holiday', 'Holiday Management'), ('worksettings', 'Work Settings Management'), ('overtimesummaryrequest', 'Overtime Summary Request Management'), ('overtimerequest', 'Overtime Request Management'), ('overtimeexporthistory', 'Overtime Export History Management'), ('attendancecorrection', 'Attendance Correction Management'), ('grouppermission', 'Group Permission Management'), ('grouppermissiontemplate', 'Group Permission Template Management'), ('generatedreport', 'Generated Report Management'), ('reportaccesslog', 'Report Access Log Management'), ('reportschedule', 'Report Schedule Management'), ('reporttemplate', 'Report Template Management'), ('notification', 'Notification Management')], max_length=30, verbose_name='Permission Type'),
        ),
    ]
